[tool.poetry]
name = "no-more-sql"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
transformers = "^4.41.2"
bitsandbytes = "^0.42"
peft = "^0.11.1"
accelerate = "^0.30.1"
datasets = "^2.19.1"
trl = "^0.8.6"
einops = "^0.8.0"
tensorboardX = "^2.6.2.2"
setuptools = "^70.0.0"
ipykernel = "^6.29.4"
matplotlib = "^3.9.0"
fire = "^0.6.0"
loguru = "^0.7.2"
langchain = "^0.3.3"
langchain-community = "^0.3.2"
sentence-transformers = "^3.1.1"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
